version: 0.2

Phases:
  install:
    commands:
      - echo "Nodependencies for a plain static site."
  build:
    commands:
      - echo "Nothing to build; packaging site assets."
  post_build:
    commands:
      - echo "deploying to s3 .."
      - aws s3 cp . s3://static-website-pipeline-124846/ --recursive
 
artifacts:
  files:
    - '**/*'
  discard-parths: no
